/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.ImageIcon;

/**
 *
 * @author Li
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public frmLogin() {
        this.setUndecorated(true);
        initComponents();
        JPLVoter.setVisible(true);
        JPLAdmin.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.loadImagens();
    }

    public void loadImagens() {
        ImageIcon Flag = new ImageIcon("Imagenes/Flag.gif");
        this.lblWallpaperFlag.setIcon(Flag);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPMain = new javax.swing.JPanel();
        JPLVoter = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        lblId = new javax.swing.JTextField();
        lblGetIntoVoter = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        btnExitAll = new javax.swing.JButton();
        lblWallpaperFlag = new javax.swing.JLabel();
        JPLAdmin = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnGetIntoAdmin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPMain.setPreferredSize(new java.awt.Dimension(450, 175));
        JPMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPLVoter.setBackground(new java.awt.Color(255, 255, 255));
        JPLVoter.setForeground(new java.awt.Color(255, 255, 255));
        JPLVoter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ingrese su numero de cedula");
        JPLVoter.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        lblId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblIdActionPerformed(evt);
            }
        });
        JPLVoter.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 260, 30));

        lblGetIntoVoter.setText("Ingresar");
        JPLVoter.add(lblGetIntoVoter, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        btnAdmin.setText("Admin");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        JPLVoter.add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, -1));

        btnExitAll.setText("Salir");
        btnExitAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitAllActionPerformed(evt);
            }
        });
        JPLVoter.add(btnExitAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 70, -1));
        JPLVoter.add(lblWallpaperFlag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 450, 180));

        JPMain.add(JPLVoter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 250));

        JPLAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ingrese su contraseña:");
        JPLAdmin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        txtPassword.setText("jPasswordField1");
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        JPLAdmin.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 300, -1));

        btnGetIntoAdmin.setText("Ingresar");
        JPLAdmin.add(btnGetIntoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        JPLAdmin.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        JPMain.add(JPLAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPMain, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPMain, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIdActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        JPLAdmin.setVisible(true);
        JPLVoter.setVisible(false);
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        JPLAdmin.setVisible(false);
        JPLVoter.setVisible(true);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnExitAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitAllActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane JPLAdmin;
    private javax.swing.JLayeredPane JPLVoter;
    private javax.swing.JPanel JPMain;
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExitAll;
    private javax.swing.JButton btnGetIntoAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton lblGetIntoVoter;
    private javax.swing.JTextField lblId;
    private javax.swing.JLabel lblWallpaperFlag;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
